[package]
name = "swcache"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
clearscreen = "3.0.0"
owo-colors = "4.1.0"
sysinfo = { version = "0.32.0", features = ["windows"] }
toml = "0.8.19"
